[pytest]
addopts = -W "ignore:unclosed database in <sqlite3\.Connection object.*:ResourceWarning"
filterwarnings =
    ignore:comprehension\.__init__ missing 1 required positional argument.*is_async.*:DeprecationWarning:pony\.
